export const skills=[
    "R",
    "java",
    "sql",
    ".net",
    ".net core",
    ".net developer",
    ".net framework",
    ".net technologies",
    "24x7",
    "2d",
    "3d",
    "3nf principles",
    "4g",
    "5g",
    "A&pp",
    "A+",
    "A3",
    "A\/b testing",
    "Abap",
    "Ab initio",
    "Ab initio etl",
    "Ab testing",
    "Abinitio",
    "Abinito",
    "Accenture",
    "Acceptance testing",
    "Access",
    "Access control",
    "Access management",
    "Accountancy",
    "Accounting",
    "Accounting configuration",
    "Accounting entries",
    "Accounting software",
    "Accounting standards",
    "Accounting systems",
    "Accounts",
    "Accounts payable",
    "Accounts receivable",
    "Acl",
    "Action plan",
    "Active directory",
    "Activemq",
    "Ad campaign",
    "Ad hoc",
    "Ad operations",
    "Adb",
    "Adf",
    "Adfs",
    "Administration",
    "Administrative assistance",
    "Ado",
    "Ado net",
    "Adobe",
    "Adobe analytics",
    "Adobe experience manager",
    "Adobe marketing cloud",
    "Adobe xd",
    "Advertising",
    "Agile",
    "Agile development",
    "Agile environment",
    "Agile methodologies",
    "Agile methodology",
    "Agile project management",
    "Agile scrum",
    "Agile software design life cycle",
    "Agile software development",
    "Agile teams",
    "Aiohttp",
    "Ajax",
    "Akka",
    "Algorithm",
    "Algorithm design",
    "Algorithm development",
    "Algorithmic trading",
    "Algorithms",
    "Alteryx",
    "Amazon aws",
    "Amazon cloud",
    "Amazon ec2",
    "Amazon s3",
    "Ambassador platforms",
    "Aml",
    "Aml analyst",
    "Amplitude",
    "Anaconda",
    "Analyst",
    "Analysis",
    "Analysis coding",
    "Analysis of data",
    "Analysis services",
    "Analytical",
    "Analytical skill",
    "Analytical skills",
    "Analytics",
    "Analytics development",
    "Analytics reporting",
    "Android",
    "Android app",
    "Android development",
    "Angular",
    "Angular 12",
    "Angular 4+",
    "Angular 9",
    "Api",
    "Api automation",
    "Api design",
    "Api development",
    "Api integration",
    "Api testing",
    "Apigee",
    "App development",
    "Application",
    "Application architecture",
    "Application deployment",
    "Application design",
    "Application development",
    "Application integration",
    "Application support",
    "Applied mathematics",
    "Athena",
    "Atlassian",
    "Audit",
    "Auditing",
    "Augmented reality",
    "Aws",
    "Aws analytics",
    "Aws api",
    "Aws architecture",
    "Aws cloud",
    "Aws cloud native",
    "Aws cloud services",
    "Aws cloudformation",
    "Aws cloudtrail",
    "Aws codebuild",
    "Aws computing",
    "Aws core services",
    "Aws crawlers",
    "Aws data",
    "Aws data base migration service",
    "Aws data engineer",
    "Aws data engineering",
    "Aws data lake",
    "Aws data migration",
    "Aws data ops",
    "Aws data pipeline",
    "Aws data pipelines",
    "Aws data services",
    "Aws data tools",
    "Aws data warehousing",
    "Aws database migration",
    "Aws database migration service",
    "Aws dms",
    "Aws ecr",
    "Aws emr",
    "Aws gateway",
    "Aws glue",
    "Aws glue athena",
    "Aws iaas",
    "Aws kinesis",
    "Aws lambda",
    "Aws lamda",
    "Aws lex",
    "Aws ml",
    "Aws or azure or google cloud",
    "Aws oracle rds",
    "Aws pyspark",
    "Aws python",
    "Aws quicksight",
    "Aws rds",
    "Aws redshift",
    "Aws s3",
    "Aws sagemaker",
    "Aws sam",
    "Aws security",
    "Aws serverless technologies",
    "Aws services",
    "Aws ses",
    "Aws snowflake",
    "Aws sns",
    "Aws spark",
    "Aws stack",
    "Aws step functions",
    "Aws transfer family",
    "Aws virtual private cloud",
    "Aws web services",
    "Aws-emr",
    "Aws/azure",
    "Aws/azure cloud",
    "Aws/azure data services",
    "Awsazure spark",
    "Awsazuregcp",
    "Aws|azure| sql",
    "Azure",
    "Azure active directory",
    "Azure adf",
    "Azure adls",
    "Azure adls gen2",
    "Azure adx",
    "Azure analysis",
    "Azure analysis services",
    "Azure analytical",
    "Azure analytics",
    "Azure analytics services",
    "Azure app",
    "Azure apps",
    "Azure architect",
    "Azure architecture",
    "Azure automation",
    "Azure aws",
    "Azure big data",
    "Azure blob",
    "Azure blob storage",
    "Azure cl",
    "Azure cli",
    "Azure cloud",
    "Azure cloud architecture",
    "Azure cloud data",
    "Azure cloud engineer",
    "Azure cloud platform",
    "Azure cloud service",
    "Azure cloud services",
    "Azure cloud systems",
    "Azure cloud technologies",
    "Azure core technologies",
    "Azure cosmos",
    "Azure data",
    "Azure data - bricks",
    "Azure data architect",
    "Azure data base",
    "Azure data bricks",
    "Azure data catalog",
    "Azure data engineer",
    "Azure data engineering",
    "Azure data factory",
    "Azure data factory pyspark databricks adls azure sql database python/scala sql",
    "Azure data flow",
    "Azure data forms",
    "Azure data functions",
    "Azure data lake",
    "Azure data lake analytics",
    "Azure data lake gen2",
    "Azure data lake services",
    "Azure data lake storage",
    "Azure data lake store",
    "Azure data lake store gen 2",
    "Azure data lake/delta lake",
    "Azure data lakes",
    "Azure data pipeline",
    "Azure data science",
    "Azure data services",
    "Azure data sql dw",
    "Azure data stack",
    "Azure data storage",
    "Azure data warehouse",
    "Azure database",
    "Azure database data bricks",
    "Azure databases",
    "Azure databricks",
    "Azure databricks admin",
    "Azure dataengineer",
    "Azure datafactory",
    "Azure datalakes",
    "Azure dev ops",
    "Azure developer",
    "Azure devops",
    "Azure dw",
    "Azure ecosystem",
    "Azure etl",
    "Azure event grid",
    "Azure event hub",
    "Azure events hub",
    "Azure file storage",
    "Azure full stack",
    "Azure functions",
    "Azure hdinsight databricks",
    "Azure information protection",
    "Azure iot",
    "Azure iot engineer (streaming data)",
    "Azure keyvalut",
    "Azure kubernetes",
    "Azure kubernetes infrastructure admin",
    "Azure logic app",
    "Azure logic apps",
    "Azure machine learning",
    "Azure ml",
    "Azure ml studio",
    "Azure modern data platform",
    "Azure native services",
    "Azure paas",
    "Azure pipelines",
    "Azure public cloud",
    "Azure python",
    "Azure repos",
    "Azure search",
    "Azure security services",
    "Azure sentinel",
    "Azure services",
    "Azure services data factory",
    "Azure spark",
    "Azure sql",
    "Azure sql data warehouse",
    "Azure sql database",
    "Azure sql datawarehouse",
    "Azure sql db",
    "Azure sql dw",
    "Azure sql dw / synapse",
    "Azure sql dwh",
    "Azure sql pools",
    "Azure sql server",
    "Azure sql warehouse",
    "Azure stack",
    "Azure stack module",
    "Azure steam analytics",
    "Azure storage",
    "Azure storage explorer",
    "Azure store",
    "Azure stream analytics",
    "Azure streaming analytics",
    "Azure streams",
    "Azure synapse",
    "Azure synapse analytics",
    "Azure synapse pool",
    "Azure synapseazure",
    "Azureml",
    "C",
    "C#",
    "C++",
    "C++python",
    "C\/c++",
    "C\/c++",
    "Cad",
    "Cadence",
    "Ca",
    "Ca erwin",
    "Cae",
    "Cassandra",
    "Cd",
    "Cdc",
    "Cdh",
    "Cdm",
    "Cdn",
    "Cdp",
    "Cdqa",
    "Celery",
    "Celonis",
    "Certified agile scrum master",
    "Certified black belt",
    "Cfd",
    "Cgi",
    "Change analyst",
    "Change delivery",
    "Change management",
    "Channel business",
    "Channel management",
    "Channel sales",
    "Cicd",
    "Cicd deployment",
    "Cicd framework",
    "Cicd pipeline",
    "Cisco",
    "Cisco routers",
    "Cloudera",
    "Cloudera data",
    "Cloudera hadoop",
    "Cloud",
    "Cloud analytics",
    "Cloud application development",
    "Cloud applications",
    "Cloud architect",
    "Cloud architecture",
    "Cloud computing",
    "Cloud data",
    "Cloud data engineer",
    "Cloud data integration",
    "Cloud data warehouse",
    "Cloud databases",
    "Cloud deployment",
    "Cloud design",
    "Cloud infrastructure",
    "Cloud management",
    "Cloud migration",
    "Cloud native",
    "Cloud platform",
    "Cloud security",
    "Cloud services",
    "Cloud solutioning",
    "Cloud spanner",
    "Cloud sql",
    "Cluster analysis",
    "Cluster management",
    "Cobol",
    "Cocoa touch",
    "Code",
    "Code development",
    "Code refactoring",
    "Code review",
    "Coding",
    "Cognos",
    "Cognos analytics",
    "Cognos reporting",
    "Compensation analysis",
    "Compensation analyst",
    "Compensation and benefits",
    "Compliance",
    "Config",
    "Configuration",
    "Configuration management",
    "Content delivery",
    "Continuous delivery",
    "Continuous integration",
    "Control management",
    "Control-m",
    "Convex optimization",
    "Core and advance python programming",
    "Core data",
    "Core databases",
    "Core finance",
    "Core hr",
    "Core innovation services",
    "Core java",
    "Core java programming",
    "Core net",
    "Core php",
    "Core python",
    "Core spark",
    "Core sql",
    "Cordova",
    "Couchbase",
    "Couchdb",
    "Cryptography",
    "Css",
    "Css3",
    "Css5",
    "Cucumber",
    "Cuda",
    "Cudnn",
    "Cyber security",
    "Cyber security analyst",
    "Cybersecurity",
    "D3",
    "D3 js",
    "D3.js",
    "Dart cross",
    "Dashboard",
    "Dashboard development",
    "Dashboard reporting",
    "Dashboard tool",
    "Dashboard tools",
    "Dask",
    "Data",
    "Data - intensive",
    "Data - sql",
    "Data - structures",
    "Data - warehousing",
    "Data acquisition",
    "Data analysis",
    "Data analysis and project management.",
    "Data analysis expressions",
    "Data analyst",
    "Data analytics",
    "Data architect",
    "Data architecture",
    "Data automation",
    "Data engineering",
    "Data extraction",
    "Data governance",
    "Data integration",
    "Data scientist",
    "Data security",
    "Database administration",
    "Database administrator",
    "Database design",
    "Database development",
    "Database engineering",
    "Database management",
    "Database management system",
    "Dataflow",
    "Dataops",
    "Dataproc",
    "Datastore",
    "Datawarehouse",
    "Date lake",
    "Dax",
    "Dax power bi",
    "Db2",
    "Dbt",
    "Debugging",
    "Deep learning",
    "Deep learning frameworks",
    "Deep learning model",
    "Deep learning modeling",
    "Deep learning models",
    "Deep troubleshooting",
  "Defect analysis",
  "Defect management",
  "Defect tracking",
  "Deliver wireframe",
  "Dev - analysis",
  "Dev - ops",
  "Develop",
  "Developer",
  "Developer trainee",
  "Developing",
  "Development",
  "Development lead",
  "Development lifecycle",
  "Development management",
  "Development manager",
  "Development testing",
  "Device driver",
  "Device tree",
  "Devops",
  "Devops engineer",
  "Devops jenkins",
  "Devops methodologies",
  "Devops pipeline",
  "Devsecops",
  "Docker",
  "Docker containerization",
  "Docker containers",
  "Docker hub",
  "Dockers",
  "Dockerization",
  "Distributed architecture",
  "Distributed computing",
  "Distributed computing tools",
  "Distributed data processing",
  "Distributed data system",
  "Distributed system",
  "Distributed systems",
  "Distributed training",
  "E - business",
  "E - commerce",
  "E commerce",
  "E-commerce",
  "E-commerce operations",
  "E-commerce seo specialist",
  "Eai",
  "Elastic mapreduce",
  "Elastic search",
  "Elasticsearch",
  "Electrical design",
  "Embedded c",
  "Embedded linux",
  "Embedded system development",
  "Embedded systems",
  "End-to-end",
  "Endpoint security",
  "Engineering",
  "Engineering data",
  "Engineering design",
  "Engineering management",
  "Engineering manager",
  "Enterprise architect",
  "Enterprise architecture",
  "Enterprise cloud",
  "Enterprise content management",
  "Enterprise data management",
  "Enterprise data warehouse",
  "Enterprise integration",
  "Enterprise reporting",
  "Etl",
  "Etl \/ elt",
  "Etl architecture",
  "Etl automation",
  "Etl cloud",
  "Etl data integration",
  "Etl design",
  "Etl developer",
  "Etl development",
  "Etl framework",
  "Etl implementation",
  "Etl testing",
  "Etl tool",
  "Etl tools",
  "Etl tuning",
  "Etrm",
  "Evaluation",
  "Event management",
  "Event monitoring",
  "Excel",
  "Excel dashboards",
  "Excel data management",
  "Excel ecc",
  "Excel functions",
  "Excel macro",
  "Excel macros",
  "Excel modeling",
  "Excel powerpoint",
  "Excel report preparation",
  "Excel sheet",
  "Excel skills",
  "Excel spreadsheet",
  "Excel vba",
  "Exception handling",
  "Faster payments",
  "Fdmee",
  "Feedback",
  "Field testing",
  "Finance erp system",
  "Financial analysis",
  "Financial data analyst",
  "Financial modeling",
  "Financial planning",
  "Financial planning and analysis",
  "Financial reporting",
  "Financial risk management",
  "Financial services",
  "Filenet",
  "Finance",
  "Finance analyst",
  "Finance executive",
  "Finance manager",
  "Financial operations",
  "Financial process",
  "Financial risk",
  "Financial risk management",
  "Financial sector",
  "Financial spreading",
  "Financial statement analysis",
  "Firebase",
  "Firebug",
  "Firehose",
  "Firewall",
  "Firmware",
  "Flash",
  "Flask",
  "Flutter",
  "Flutter mobile uis",
  "Flink",
  "Flow",
  "Flume",
  "Front-end",
  "Front-end technologies",
  "Front end",
  "Front end developer",
  "Frameworks",
  "Full stack",
  "Full stack application development",
  "Full stack developer",
  "Full stack development",
  "Full-stack dev",
  "Full-stack developer",
  "Fullstack development",
  "Gcp",
  "Gcp analytics",
  "Gcp and aws",
  "Gcp bigquery",
  "Gcp cloud",
  "Gcp data engineer",
  "Gcp dataflow",
  "Gcp hadoop & hadoop",
  "Gcp infra",
  "Gcp stack",
  "Gcp storage",
  "Gcp/azure/aws db",
  "Git",
  "Git big",
  "Git workflows",
  "Gitbun ci",
  "Github",
  "Gitlab",
  "Google",
  "Google adwords",
  "Google ai platform",
  "Google analytics",
  "Google analytics 360",
  "Google apis",
  "Google app engine",
  "Google apps",
  "Google big",
  "Google big query",
  "Google bigquery",
  "Google cloud",
  "Google cloud azure",
  "Google cloud data",
  "Google cloud data services",
  "Google cloud platform",
  "Google cloud platforms",
  "Google cloud sdk",
  "Google cloud server",
  "Google cloud storage",
  "Google colab",
  "Google data fusion",
  "Google data studio",
  "Google kubernetes",
  "Google kubernetes engine",
  "Google pub",
  "Google scripting",
  "Google sheets",
  "Google spreadsheet",
  "Graphql",
  "Grafana",
  "Grid",
  "Groovy",
  "Grpc",
  "Gsm",
  "Gst",
  "Gtm",
  "Gts",
  "Guidewire application development",
  "Guidewire claims",
  "Guidewire platform",
  "Guidewire products",
  "Hadoop",
  "Hadoop administration",
  "Hadoop developer",
  "Hadoop development",
  "Hadoop ecosystem",
  "Hadoop hive",
  "Hadoop map reduce",
  "Hadoop spark",
  "Hadoop testing",
  "Hbase",
  "Hcm",
  "Hibernate",
  "Html",
  "Html 5",
  "Html/css",
  "Html and css",
  "Html5",
  "Html5+",
  "Http",
  "Hubspot",
  "Hudi",
  "Human resources",
  "Hyper-v",
  "Hyperion",
  "Iaas",
  "Iam",
  "Iam cloud operations",
  "Ibm",
  "Ibm cognos tm1",
  "Ibm data stage",
  "Ibm datapower",
  "Ibm mq",
  "Ibm tivoli monitoring",
  "Ibm watson",
  "Ibm websphere",
  "Ibpm",
  "Ifrs",
  "Informatica",
  "Informatica power center",
  "Information security",
  "Information technology",
  "Infosphere",
  "Infosphere datastage",
  "Infrastructure",
  "Infrastructure as code",
  "Infrastructure automation",
  "Infrastructure management",
  "Infrastructure modeling",
  "Infrastructure security",
  "Infrastructure services",
  "Integration",
  "Integration - testing",
  "Integration analyst",
  "Integration php",
  "Integration runtime services",
  "Integration services",
  "Integration testing",
  "Intellectual property",
  "Intelligence",
  "Intellij",
  "Intellij idea",
  "Interaction design",
  "Interface testing",
  "Interfaces",
  "Intern",
  "Internal audit",
  "Internal audit consulting",
  "Internal auditor",
  "Internet banking",
  "Internet research",
  "Internet technologies",
  "Internship",
  "Interpersonal communication",
  "Interpersonal skills",
  "Interviewing",
  "Intranet",
  "Intrusion detection",
  "Inventory",
  "Inventory control",
  "Inventory management",
  "Inventory reconciliation",
  "Investment",
  "Investment advisory",
  "Investment analytics",
  "Investment banking",
  "Investment banking operations",
  "Investment management",
  "Investment portfolio",
  "Investment research",
  "Investment risk",
  "Investment strategies",
  "Investor relations",
  "Invoice processing",
  "Invoicing",
  "Ionic",
  "Ios",
  "Ios development",
  "Ios ipa",
  "Ios native",
  "Ios sdk",
  "Iot",
  "Iot application development",
  "Ip",
  "Ip addressing",
  "Ip analyst",
  "Ip routing",
  "Ipo",
  "Ipr",
  "Ipro",
  "Ips",
  "Ipv6",
  "Ise",
  "Is security",
  "Ism",
  "Iso",
  "Iso 13485",
  "Iso 20000",
  "Iso 27001",
  "Iso 27001 lead auditor",
  "Iso 9001",
  "Isomorphic react",
  "Iss",
  "Issue resolution",
  "It",
  "It analysis",
  "It analyst",
  "It applications support",
  "It asset management",
  "It automation tools",
  "It business",
  "It business analysis",
  "It business analyst",
  "It compliance",
  "It consulting",
  "It executive",
  "It facilities",
  "It fresher",
  "It hardware",
  "It infrastructure",
  "It lead",
  "It management",
  "It marketing",
  "It operations",
  "It product development",
  "It project",
  "It project delivery",
  "It project management",
  "It recruiters",
  "It recruitment",
  "It risk",
  "It risk assessment",
  "It risk management",
  "It sales",
  "It security",
  "It security analyst",
  "It service management support",
  "It services",
  "It services & consulting",
  "It skills",
  "It sourcing",
  "It sourcing business analyst",
  "It staffing",
  "It strategy",
  "It strategy planning",
  "It support",
  "It transformation",
  "Iterative",
  "Itil",
  "Itil framework",
  "Itil process",
  "Itil processes",
  "Itl",
  "Itsm",
  "Ivr",
  "J2ee",
  "J2ee stack",
  "Jamf",
  "Java",
  "Java & lambdas",
  "Java 6",
  "Java 7",
  "Java 8",
  "Java application",
  "Java azure",
  "Java backend",
  "Java cloud",
  "Java db technologies",
  "Java developer",
  "Java ee",
  "Java enterprise",
  "Java framework",
  "Java fs",
  "Java fullstack",
  "Java j2ee developer",
  "Java mapreduce",
  "Java or python",
  "Java plus",
  "Java programming",
  "Java script",
  "Java scripts",
  "Java software engineer",
  "Java spring framework",
  "Java tech stack",
  "Java web services",
  "Java\/golang\/kotlin",
  "Java\/python",
  "Java\/python\/scala",
  "Java\/python\/spark",
  "Javamr",
  "Javascript",
  "Javascript frameworks",
  "Javascript\/html5\/css",
  "Jax - rs",
  "Jax - ws",
  "Jaxb",
  "Jboss",
  "Jcl",
  "Jd edwards",
  "Jda esp",
  "Jdbc",
  "Jdbs",
  "Jee",
  "Jenkin",
  "Jenkins",
  "Jersey",
  "Jest",
  "Jinja 2",
  "Jira",
  "Jmeter",
  "Jmp",
  "Jms",
  "Job analysis",
  "Job evaluation",
  "Join",
  "Journalism",
  "Jpa",
  "Jquery",
  "Js",
  "Js rest api",
  "Json",
  "Json web token",
  "Jsp",
  "Jsp technologies",
  "Jtag",
  "Julia",
  "Junior analyst",
  "Junior data analyst",
  "Junior executive",
  "Junior research analyst",
  "Junior staff",
  "Juniper",
  "Junit",
  "Jupyter",
  "Jupyter notebook",
  "Jupyterlab",
  "Jvm",
  "Jwt",
  "Jython",
  "K8s",
  "Kafka",
  "Kafka and kafka",
  "Kafka architecture",
  "Kafka broker",
  "Kafka cloud",
  "Kafka event bus",
  "Kafka rabbit mq",
  "Kafka rabbitmq",
  "Kafka solutions snow flak data engineer big data hadoop hive hdfs data lakes",
  "Kafkainput",
  "Kaizen",
  "Kakfa",
  "Kanban",
  "Karma",
  "Kdb",
  "Kedro",
  "Kerala",
  "Keras",
  "Kerberos",
  "Kernel",
  "Key account management",
  "Key accounts",
  "Key management",
  "Key skills",
  "Keyword analysis",
  "Kibana",
  "Kinesis",
  "Knime",
  "Knn",
  "Know your customer",
  "Knowledge management",
  "Knowledge of big data stackdata modelling",
  "Knowledge of computers",
  "Knowledge of ms office",
  "Kong",
  "Koras",
  "Kotlin",
  "Kpi",
  "Kpis",
  "Kpo",
  "Ksql",
  "Kstream",
  "Kstreams",
  "Kubeflow",
  "Kubernates",
  "Kubernetes",
  "Kubernetes architecture and design",
  "Kubernetes microservices",
  "Kubernetes service *ml",
  "Kubernetes services",
  "Malware analysis",
  "Malware dos",
  "Managed services",
  "Manager information technology",
  "Manager internal audit",
  "Manager presales",
  "Manager program management",
  "Manager quality assurance",
  "Manager quality control",
  "Manager technology",
  "Manual testing",
  "Manufacturing data scientist",
  "Manufacturing engineering",
  "Manufacturing operations",
  "Manufacturing process",
  "Map reduce",
  "Mapreduce programming",
  "Mongodb",
  "Ms azure",
  "Ms azure data management",
  "Ms bi",
  "Ms sql",
  "Ms sql server",
  "Ms sql server dba",
  "Ms sql server reporting services",
  "Mulesoft",
  "Mulesoft anypoint api platform",
  "Multithreading",
  "Music production",
  "Mvc",
  "Network administration",
  "Network analysis",
  "Network design",
  "Network infrastructure",
  "Network management",
  "Network monitoring",
  "Network programming",
  "Network security",
  "Neural networks",
  "Next.js",
  "Nginx",
  "Nifi",
  "Nlp",
  "Nlp algorithms",
  "Nlp and dialog systems",
  "Nlp communication",
  "Nlp models",
  "Nlp python/r pyspark cloud/azure aws gcp data scientist data science",
  "Nlp/python/r",
  "Nltk",
  "Nlu",
  "Node",
  "Node.js",
  "Nodejs",
  "Nodejs/typescript",
  "Nodejs framework",
  "Nosql",
  "Nosql databases",
  "Nosql db",
  "Nosql dbs",
  "Nosql technologies",
  "Npm",
  "Numpy",
  "Numpy stack",
  "Objective c",
  "Object detection",
  "Object oriented analysis",
  "Object oriented analysis & design",
  "Object oriented coding",
  "Object oriented design",
  "Object oriented development",
  "Object oriented modeling",
  "Object oriented programming",
  "Object relational mapper",
  "Oracle",
  "Oracle 10g dataguard",
  "Oracle 9i",
  "Oracle agile",
  "Oracle analytics",
  "Oracle application server",
  "Oracle apps",
  "Oracle business intelligence",
  "Oracle coherence",
  "Oracle data analyst",
  "Oracle data integrator",
  "Oracle database",
  "Oracle db",
  "Oracle dba",
  "Oracle designer",
  "Oracle developer",
  "Oracle e",
  "Oracle edw",
  "Oracle epm",
  "Oracle erp",
  "Oracle etl",
  "Oracle financials",
  "Oracle financials cloud",
  "Oracle fusion",
  "Oracle fusion middleware",
  "Oracle hcm",
  "Oracle hcm cloud",
  "Oracle pl/sql",
  "Oracle ppm cloud",
  "Oracle procedural",
  "Oracle relational databases.",
  "Oracle service bus",
  "Oracle soa",
  "Oracle sql",
  "Oracle support",
  "Oracle teradata",
  "Oracle vcp",
  "Orc",
  "Orc protobuf",
  "Orogle relational databases.",
  "P & l",
  "Pa/om",
  "Paas",
  "Palantir",
  "Pandas",
  "Parallel programming",
  "Pardot",
  "Parse",
  "Pascal",
  "Pattern recognition",
  "Pay per click",
  "Payment gateway",
  "Payment processing",
  "Payments",
  "Pcb design",
  "Pci",
  "Pcie",
  "Pcm",
  "Pcmcs",
  "Pde",
  "Pdf",
  "Pdm",
  "Pentaho",
  "People analytics",
  "People development",
  "People management",
  "People management skills",
  "People skills",
  "Perforce",
  "Performance analysis",
  "Performance testing",
  "Perl",
  "Pf sense",
  "Phishing",
  "Php",
  "Physical design",
  "Physics",
  "Pig",
  "Pipeline",
  "Pivot table",
  "Pl-sql",
  "Pl/sql and standard rdbmss",
  "Planning",
  "Plant engineering",
  "Platform",
  "Playbook",
  "Plc",
  "Pmi acp",
  "Pmo",
  "Pmo analyst",
  "Pmo management",
  "Pmp",
  "Postgres",
  "Postgresql",
  "Postgresql administration",
  "Power",
  "Power bi",
  "Power bi dashboards",
  "Power bi desktop",
  "Power bi development",
  "Power bi reports",
  "Power shell",
  "Powerapps",
  "Powerbi",
  "Powerbi desktop",
  "Powerpoint",
  "Powershell",
  "Predictive analysis",
  "Predictive analytics",
  "Pricing analysis",
  "Primary market research",
  "Primavera",
  "Principal data scientist",
  "Problem solving",
  "Proc sql",
  "Process analysis",
  "Process analyst",
  "Process automation",
  "Process control",
  "Programming",
  "Programming languages",
  "Programming skills",
  "Python",
  "Java",
  "Node.js",
  "React",
  "React Native",
  "Redux",
  "JavaScript",
  "SQL",
  "Database design",
  "Data analysis",
  "Data science",
  "Data engineering",
  "Web development",
  "Mobile app development",
  "Software development",
  "API development",
  "RESTful APIs",
  "Microservices",
  "Cloud computing",
  "AWS",
  "Azure",
  "Git",
  "Version control",
  "Linux",
  "Unix",
  "Shell scripting",
  "DevOps",
  "Agile",
  "Scrum",
  "CI/CD",
  "Machine learning",
  "Artificial intelligence",
  "Cybersecurity",
  "Network security",
  "Blockchain",
  "Databases",
  "Data modeling",
  "Software architecture",
  "UI/UX design",
  "Automation testing",
  "Quality assurance",
  "IT support",
  "Troubleshooting",
  "System administration",
  "Network administration",
  "Web services",
  "REST API design",
  "Microservices architecture",
  "Containerization",
  "Docker",
  "Kubernetes",
  "Rf",
    "Rfi",
    "Rfp",
    "Rfps",
    "Rfq",
    "Rfx",
    "Rice",
    "Rich snippets",
    "Risk",
    "Risk analysis",
    "Risk analysis testing",
    "Risk analyst",
    "Risk analytics",
    "Risk assessment",
    "Risk assessments",
    "Risk compliance",
    "Risk consulting",
    "Risk engineering",
    "Risk functions",
    "Risk governance",
    "Risk management",
    "Risk mitigation",
    "Risk modeling",
    "Risk monitoring",
    "Risk reporting",
    "Risklink",
    "Riversand",
    "Rllib",
    "Rls",
    "Rnn",
    "Rnns",
    "Robot framework",
    "Robotics",
    "Robotics process automation",
    "Roc",
    "Rollovers",
    "Root - cause analysis",
    "Root cause",
    "Root cause analysis",
    "Router",
    "Routing",
    "Routing & switching",
    "Rpa",
    "Rpa technologies",
    "Rpc",
    "Rpo",
    "Rs",
    "Rsa",
    "Rsa archer",
    "Rshiny",
    "Rss",
    "Rta",
    "Rtcp",
    "Rtos",
    "Rtr",
    "Ruby",
    "Ruby on rails",
    "Ruby rails",
    "Runmyjobs",
    "Rust",
    "Rwa",
    "Rxjava",
    "Rxswift",
    "Sparkpyspark",
    "Sparkql",
    "Sparksql",
    "Sparql",
    "Spatial data analysis",
    "Spec",
    "Speech analytics",
    "Speech mining",
    "Speech recognition",
    "Speech synthesis",
    "Sperk",
    "Spinnaker",
    "Splunk",
    "Splunk admin",
    "Splunk es",
    "Splus",
    "Spoken english",
    "Sports prediction",
    "Spotfire",
    "Sprak",
    "Spreadsheets",
    "Spring",
    "Spring batch",
    "Spring boot",
    "Spring framework",
    "Spring frameworks",
    "Spring mvc",
    "Spring security",
    "Springboot",
    "Springboot java",
    "Springmvc",
    "Sprinklr",
    "Sprint",
    "Sprint boot",
    "Sprint planning",
    "Sprint process",
    "Spss",
    "Spss modeller",
    "Spss statistics",
    "Sqa",
    "Sql",
    "Sql - designing tables",
    "Sql alchemy",
    "Sql analyst",
    // ... (more skills related to dev/IT)
    "Textblob",
    "Tez",
    "Tfs",
    "Tfserve",
    "Tfvc",
    "The",
    "The hcp360 rep dashboard",
    "Theano",
    "Thermal",
    "Third party",
    "Thoughtspot",
    "Threaded",
    "Threat",
    "Threat analyst",
    "Thunk",
    "Thymeleaf",
    "Tibco",
    "Tibco data virtualization",
    "Tibco spotfire",
    "Ticketing",
    "Ticketing tool",
    "Tickstack",
    "Tier 3-4 support",
    "Time",
    "Time management",
    "Time series",
    "Time series analysis",
    "Time series data",
    "Time series forecasting",
    "Timescale",
    "Titan",
    "Tomcat",
    "Torch",
    "Tosca testing",
    "Traceability matrix",
    "Trading system",
    "Trainer",
    "Training",
    "Training & development",
    "Training analysis",
    "Training and development",
    "Training delivery",
    "Training management",
    "Training methodologies",
    "Training needs",
    "Transact sql",
    "Transaction analysis",
    "Transaction management",
    "Transaction monitoring",
    "Transaction processing",
    "Transcription",
    "Transfer learning",
    "Transform",
    "Transform and load",
    "Transformation",
    "Transformers",
    "Translation",
    "Translator",
    "Transport management system",
    "Travel",
    "Treasury",
    "Treasury operations",
    "Trend analysis",
    "Trend forecasting",
    "Trouble shooting",
    "Troubleshooting",
    "Tsne",
    "Tsql",
    "Tsql development",
    "Tsql queries",
    "Tuning",
    "Typescript",
    "U - sql",
    "Ui",
    "Ui / ux",
    "Ui / ux design",
    "Ui / ux designers",
    "Ui architecture",
    "Ui data",
    "Ui design",
    "Ui development",
    "Ui path",
    "Ui path developer",
    "Ui script",
    "Ui technologies",
    "Ui ux development",
    "Uikit",
    "Uima",
    "Uipath",
    "Umap",
    "Uml",
    "Underwriting",
    "Unit test",
    "Unit testing",
    "Unit testing framework",
    "Unittest",
    "Unix",
    "Unix administration",
    "Unix linux",
    "Unix operating system",
    "Unix os",
    "Unix scripting",
    "Unix scripts",
    "Unix shell scripting",
    "Unix shell scripts",
    "Unix / linux",
    "Unixlinux systems",
    "Ups",
    "Usability testing",
    "Use cases",
    "User acceptance testing",
    "User experience",
    "User experience design",
    "User interface",
    "User interface designing",
    "User interface testing",
    "User research",
    "User stories",
    "User support",
    "User-centered design",
    "Utilities",
    "Ux",
    "Ux design",
    "Ux designer",
    "Ux research",
    "Validation",
    "Value analysis",
    "Vapt",
    "Var",
    "Variance analysis",
    "Vb",
    "Vb script",
    "Vb scripting",
    "Vba",
    "Vba access",
    "Vba automation",
    "Vba coding",
    "Vba excel",
    "Vba microsoft access",
    "Version control",
    "Version control system",
    "Vlan",
    "Vlookup",
    "Vmware",
    "Vmware administrator",
    "Vmware and / or kubernetes",
    "Voice",
    "Voip",
    "Vuejs",
    "Vulnerability",
    "Vulnerability assessment",
    "Vulnerability management",
    "Wan",
    "Web analytic",
    "Web analytics",
    "Web api",
    "Web application",
    "Web application development",
    "Web application firewall",
    "Web application testing",
    "Web architecture",
    "Web crawling",
    "Web designing",
    "Web development",
    "Web framework",
    "Web frameworks",
    "Web hosting",
    "Web operations",
    "Web platforms",
    "Web proxies",
    "Web research",
    "Web scraping",
    "Web scrapping",
    "Web servers",
    "Web service",
    "Web services",
    "Web services development",
    "Web services testing",
    "Web technologies",
    "Web testing",
    "Web tools",
    "Web visualization",
    "Web2py",
    "Webfocus",
    "Webhooks",
    "Weblogic",
    "Webpack",
    "Webservice",
    "Webservices",
    "Website",
    "Website management",
    "Wellness",
    "White box testing",
    "Whitebox",
    "Windows",
    "Windows 2008",
    "Windows administration",
    "Windows os",
    "Windows server",
    "Windows server administrator",
    "Windows server configuration",
    "Windows workflow foundation",
    "Winforms",
    "Wireframe",
    "Wireless",
    "Wireless protocol",
    "Wmi",
    "Wordpress",
    "Workday",
    "Workflow",
    "Workflow analysis",
    "Workflow diagrams",
    "Workflow management",
    "Workforce administration",
    "Workforce analytics",
    "Workforce management",
    "Workforce planning",
    "Wpf",
    "Xml",
    "Xpath",
    "Yaml",
    "Zabbix administration",
    "Zephyr",
    "Zeplin",
    "Zookeeper",
    "Zookeeper hive",
    "Zookeepers",
    "git"]